### ISSUE TITLE
Add proper copyrights everywhere or we are going to DMCA every repo on every website to hell.

### ISSUE THREAD

**Issue by Fabi** [blizzless/blizzless-diiis#11]

**Comment by BloodySlave** [comment]
Чел кринжанул

**Comment by ZLOFENIX** [comment]
Это он так пытается намекнуть что какой-то код сперт из его реп? Или просто дебил?

**Comment by BloodySlave** [comment]
Второе походу

**Comment by instant0** [comment]
Fabi is a troll.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
So basicly this person the type that gets excited and turning on about from him/herself... 

IF you post something like this, at least give description, or that what is your problem... Without it no one knows what do you want or who the hell you are.

**Comment by BloodySlave** [comment]
> Fabi is a troll.

bad trolling in last time

**Comment by Fabi** [comment]
Many code parts in here are stolen from multiple places. The authors of this project know where and they will enjoy their DMCA if they do not fix copyrights/sources.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
> Many code parts in here are stolen from multiple places. The authors of this project know where and they will enjoy their DMCA if they do not fix copyrights/sources.

Then share/adress the parts that YOU have problem with, to be mentioned.... or this is not  your code? Then why are you talking in something that you are not concerned by??

**Comment by Fabi** [comment]
> > Many code parts in here are stolen from multiple places. The authors of this project know where and they will enjoy their DMCA if they do not fix copyrights/sources.
> 
> Then share/adress the parts that YOU have problem with, to be mentioned.... or this is not your code? Then why are you talking in something that you are not concerned by??

Don't even start arguing. People behind this project know what sources are involved. Solve it or enjoy the consequences

**Comment by 0P3N50URC3-F0R3V3R** [comment]
> > > Many code parts in here are stolen from multiple places. The authors of this project know where and they will enjoy their DMCA if they do not fix copyrights/sources.
> > 
> > 
> > Then share/adress the parts that YOU have problem with, to be mentioned.... or this is not your code? Then why are you talking in something that you are not concerned by??
> 
> Don't even start arguing. People behind this project know what sources are involved. Solve it or enjoy the consequences

Then don't even start a topics. People behind your monitor should have better thing to do. You will enjoy the consequences also.... XD

**Comment by advocaite** [comment]
are you talking about how this originally derived from moooge at some point.

**Comment by pr701** [comment]
No proofs is provided
