### ISSUE TITLE
[Github permissions for regular users] Cannot reopen closed issues that are not yet fixed

### ISSUE THREAD

**Issue by Sidefix** [blizzless/blizzless-diiis#122]
I have a couple of issues that have been closed that I have more information on and context, and I cannot reopen them for review.

References:
#77 
#16

**Comment by iamdroppy** [comment]
sure, reopening them, my bad, but you could still reply on them, doesn't mean it's discarded

**Comment by iamdroppy** [comment]
I'll close this one.
