### ISSUE TITLE
Monster HP bug (?)

### ISSUE THREAD

**Issue by ggwpsayori** [blizzless/blizzless-diiis#124]
hi all.

My friend and I had such a problem - when we play alone on the minimum difficulty, the mobs have 12-15 hp, and the character's attack damage is 3-10 - everything seems to be in order.

But as soon as we enter the open game, the mobs already have about 300 hp, with the same attack values. 

So, how can we fix this? Because it's not very interesting to kill a pack of 3 mobs in 3 minutes.

**Comment by iamdroppy** [comment]
In the [config.ini file](https://github.com/blizzless/blizzless-diiis/blob/community/configs/config.ini) you have several options to increase or decrease the mobs vitality or your own own.

[Read this](https://github.com/blizzless/blizzless-diiis/blob/community/docs/game-world-settings.md)

The default options aren't really balanced IMHO.

`RateMonsterHP`, `RateMonsterDMG` are the default ones for mobs!

These are especially for your player:

```ini
; player attribute modifier
StrengthMultiplier = 1
StrengthParagonMultiplier = 1
DexterityMultiplier = 1
DexterityParagonMultiplier = 1
IntelligenceMultiplier = 1
IntelligenceParagonMultiplier = 1
VitalityMultiplier = 1
VitalityParagonMultiplier = 1
```

We're actively [contributing at the community branch](https://github.com/blizzless/blizzless-diiis/tree/community), so make sure you are using this branch. We can fix it easily in case it's a bug.

out of curiosity, what level are you and your friend at?

**Comment by ggwpsayori** [comment]
> 

we have accounts of the first levels - just created
