### ISSUE TITLE
[Question] Does I need installed game to runs a server?

### ISSUE THREAD

**Issue by LeFFaQ** [blizzless/blizzless-diiis#129]
My friends requested me to run server on dedicated VPS. So I followed the instructions, the server started but got error:

![image](https://user-images.githubusercontent.com/57927855/220980922-62f282dc-57c3-44a3-91b7-109f4de470bb.png)

Does I need installed game on my machine?

Edit: Runs on Windows 11 64-bit, PostgreSQL 9.5.25 build 1800 64-bit, precompiled from [forkas/blizzless-diiis](https://github.com/Forkas/blizzless-diiis) repo

**Comment by morriscox** [comment]
No. I have the server installed in a VM and I'm in the game now (on the machine hosting the VM.)
