### ISSUE TITLE
Проблема с настройкой игры по сети.

### ISSUE THREAD

**Issue by fransdeston** [blizzless/blizzless-diiis#14]
Доброго времени суток.

Собираем сервер для игры компанией, не можем настроить подключение к серверу из Локальной сети.

Файл конфигурации для изменения настроек не подгружается никаким образом. Поправили конфиги каждого элемента руками. Запускается с нужными параметрами, и фиксирует запрос пользователя:
![Request](https://user-images.githubusercontent.com/29183791/185676649-5fdd8d9b-5654-4b08-b5b9-1ca183e75e57.jpg)

Но клиенту выдает ошибку при подключении:

![Error](https://user-images.githubusercontent.com/29183791/185676703-c465e07d-a60e-4f8c-8cee-37ae8a9433f3.jpg)

Очень бы хотелось понять, куда нужно класть config файл с настройками, чтобы программа сама считывала их, есть вариант, что не все настройки руками были исправлены как нужно...

**Comment by fransdeston** [comment]
Понял как скармливать настройки, но все равно ошибка остается.

**Comment by iEvengel** [comment]
Потому-что не установлен сертификат на других компьютерах. Установи на всех клиентских машинах.
