### ISSUE TITLE
 Actor asset not found

### ISSUE THREAD

**Issue by Artem89233** [blizzless/blizzless-diiis#147]
Привет всем! Я заметил то что в логах у меня не прогружаются какие то асеты. Это нормально или нет?
...

> │ 09/04/2023 16:58:11    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations BNet, GameAccount, 8                  │       │09/04/2023 16:58:12    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 3                    │
> │ 09/04/2023 16:58:11    │   MethodTrace │ ResourceService              │ GetContentHandle(): ProgramId: 0x0000424E StreamId: 0x61706674                                                                                            │       │
> │ 09/04/2023 16:58:11    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 6                    │       │09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:11    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 11                   │       │09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:11    │   MethodTrace │ ResourceService              │ GetContentHandle(): ProgramId: 0x00004433 StreamId: 0x72707273                                                                                            │       │
> │ 09/04/2023 16:58:12    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 3                    │       │09/04/2023 16:58:34    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 3                    │
> │ 09/04/2023 16:58:33    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, Party, 1                          │      ...
> │ 09/04/2023 16:58:11    │   MethodTrace │ ResourceService              │ GetContentHandle(): ProgramId: 0x0000424E StreamId: 0x61706674                                                                                            │       │
> │ 09/04/2023 16:58:11    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 6                    │       │09/04/2023 16:58:33    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, Party, 4                          │
> │ 09/04/2023 16:58:11    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 11                   │       │09/04/2023 16:58:34    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 3                    │
> │ 09/04/2023 16:58:11    │   MethodTrace │ ResourceService              │ GetContentHandle(): ProgramId: 0x00004433 StreamId: 0x72707273                                                                                            │       │
> │ 09/04/2023 16:58:12    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, GameAccount, 3                    │       │09/04/2023 16:58:40    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, Party, 2                          │
> │ 09/04/2023 16:58:33    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, Party, 1                          │       │09/04/2023 16:58:40    │   MethodTrace │ PresenceService              │ Update(): DiIiS_NA.LoginServer.Battle.BattleClient { GameAccount:  {icon:bnet} Testt#8811 [lowId: 2] } - 1 Operations D3, Party, 2                          │
> ...
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> ...
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:331                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:331                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:44    │         Trace │ Scene                        │ Actor asset not found, Method: Generate() - Generate() in WorldGenerator.cs:341                                                                           │       │
> │ 09/04/2023 16:58:45    │         Trace │ ActorFactory                 │ Actor asset not found, Method: LazyCreate() - LazyCreate() in ActorFactory.cs:35                                                                          │       │
> │ 09/04/2023 16:58:45    │         Trace │ Game                         │ AddOnLoadWorldAction: a1dun_spidercave_02                                                                                                                 │       │
> │ 09/04/2023 16:58:45    │         Trace │ Game                         │ AddOnLoadWorldAction: trdun_butcherslair_02                                                                                                               │       │
> │ 09/04/2023 16:58:45    │         Trace │ Game                         │ AddOnLoadWorldAction: a4dun_spire_exterior                                                                                                                │       │
> │ 09/04/2023 16:58:45    │         Trace │ Portal                       │ Portal _g_portal_ladder_short_orange has incomplete definition                                                                                            │       │
> │ 09/04/2023 16:58:45    │          Warn │ Portal                       │ Портал - _g_portal_ladder_short_orange Не определён до конца, исполнение функции ''умного'' вычисления для выхода.                                        │       │
> │ 09/04/2023 16:58:45    │   MethodTrace │ World                        │ SpawnMonster(): Spawning monster _waypoint at X:931.4800, Y:1172.2400 Z:-14.7000                                                                          │       │
> │ 09/04/2023 16:58:45    │         Trace │ Game                         │ AddOnLoadWorldAction: a3dun_azmodan_arena                                                                                                                 │       │
> │ 09/04/2023 16:58:45    │         Trace │ Game                         │ AddOnLoadWorldAction: a3_battlefields_03                                                                                                                  │       │
> │ 09/04/2023 16:58:45    │          Info │ GameMessage                  │ Client test@, joined game.                                                                                                                                │       │
> │ 09/04/2023 16:58:45    │   MethodTrace │ GSBackend                    │ PlayerJoined(): gameId 10131                                                                                                                              │       │
> │ 09/04/2023 16:58:46    │         Trace │ BattleBackend                │ Message received from 192.168.1.147:49180: gpj|10131                                                                                                      │       │
> │ 09/04/2023 16:58:46    │   MethodTrace │ Game                         │ SaveQuestProgress(): Broadcasting to players                                                                                                              │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │         Trace │ Spawner                      │ Triggered spawner with no ActorToSpawnSNO found.                                                                                                          │       │
> │ 09/04/2023 16:58:46    │   MethodTrace │ QuestManager                 │ AutoSetQuestMarker(): 0 triggers found on OpenWorld - quest 312429 step 2                                                                                 │       │
> │ 09/04/2023 16:58:46    │         Trace │ QuestManager                 │ (Advance) Game 10131 Advanced to quest 312429, step 2                                                                                                     │       │
> │ 09/04/2023 16:59:01    │         Trace │ InteractiveNPC               │  (OnTargeted) the npc has dynID 98 and Actor snoId _x1_lr_nephalem, ConversationList - 363730                                                             │       │
> │ 09/04/2023 16:59:02    │         Trace │ InteractiveNPC               │  (OnTargeted) the npc has dynID 100 and Actor snoId _p2_hq_zoltunkulle,                                                                                   │       │
> │ 09/04/2023 16:59:10    │          Warn │ GameClient                   │ BoolDataMessage - ID:183 has no consumer or self-handler.                                                                                                 │       │
> │ 09/04/2023 16:59:12    │         Trace │ RPCTransfer                  │ Removing disconnected subscriber DiIiS_NA.LoginServer.Battle.BattleClient                                                                                 │       │
> │ 09/04/2023 16:59:12    │   MethodTrace │ GSBackend                    │ PlayerLeft(): gameId 10131                                                                                                                                │       │
> │ 09/04/2023 16:59:12    │   MethodTrace │ GSBackend                    │ CheckConversationCriteria(): gameAccountId 2, convId 430146                                                                                               │       │
> │ 09/04/2023 16:59:12    │         Trace │ BattleBackend                │ Message received from 192.168.1.147:49180: gpl|10131                                                                                                      │       │
> │ 09/04/2023 16:59:12    │         Trace │ BattleBackend                │ Message received from 192.168.1.147:49180: ccc|2/430146                                                                                                   │       │
> │ 09/04/2023 16:59:12    │          Info │ Game                         │ All players disconnected, game session closed

В конце я вышел

**Comment by DeKaN** [comment]
Это происходит, когда для "в 40% спаун монстра Х, в 60% - нет спауна" выпадает второй случай (там указан actor `-1`, невалидный)

**Comment by iamdroppy** [comment]
> Это происходит, когда для "в 40% спаун монстра Х, в 60% - нет спауна" выпадает второй случай (там указан actor `-1`, невалидный)

Translation:
> This happens when in the case of "in 40% spawn monster X, in 60% - no spawn," the second scenario occurs (where actor -1, an invalid one, is specified).

Closing as it's idle.

**Comment by DeKaN** [comment]
@iamdroppy it has been fixed [here](https://github.com/blizzless/blizzless-diiis/pull/144/files#diff-a831f9c9d7403d067ff8ef913053119c117a0fd7245e7620e9785b732e285189)
