### ISSUE TITLE
specific version

### ISSUE THREAD

**Issue by Hiei-YYH** [blizzless/blizzless-diiis#150]
removed

i was able to make it work with the latest battlenet version by just compiling myself, i had downloaded some other version from past september. (too bad it has all the hassle to download Visual Basic and all that shit, maybe you can just build and post for others like me?)

**Comment by ketsmen** [comment]
You are a dog?

**Comment by Hiei-YYH** [comment]
> You are a dog?

no, i just find that having to download all those things even when i'm no developer/programmer just to compile a file that I did 
 in less than 10 seconds wasn't needed... the author or whoever manage the project can do it without problems. 
 Anyway, adm can close it.
