### ISSUE TITLE
1 hp damage

### ISSUE THREAD

**Issue by zzWerOk** [blizzless/blizzless-diiis#153]
Проблема в том, что мобы наносят урон в размере 1-2hp по герою. Сначала я думал что это пролог, пройду и будет нормально, но нет.
config.ini правил, выставлял RateMonsterDMG = 100 - результат один и то же. Даже переименовывал этот файл, ноль изменений.

Как мне исправить ситуацию?

**Comment by iamdroppy** [comment]
Please, check:
https://github.com/blizzless/blizzless-diiis/blob/community/docs/game-world-settings.md

Also, you can use `!difficulty up` command to increase difficulty (or before entering a game);
And player attribute modifiers from the link above.
