### ISSUE TITLE
How to resolve this error

### ISSUE THREAD

**Issue by mahaoqqsx** [blizzless/blizzless-diiis#19]
* Database was not configured through Database method.
  * No mappings were configured through the Mappings method.

**Comment by advocaite** [comment]
use community branch install docker and the instructions are in the readme 

if you followed the readme instructions this would not happen, basically your database is not setup properly

**Comment by mahaoqqsx** [comment]
I use the master branch 
This branch fixes some problems

**Comment by mahaoqqsx** [comment]
I deployed with windows 
Unable to install docker

**Comment by mahaoqqsx** [comment]
Problem solved

My world database did not change the password
Close this issue
