### ISSUE TITLE
What about the people who don't know how to do this?

### ISSUE THREAD

**Issue by VelirzX** [blizzless/blizzless-diiis#2]
Not a lot of people are gonna want to deal with this. Are there any plans to make this easier?

**Comment by advocaite** [comment]
if you want to work on fixing and building server then you shouldlearning this

**Comment by v317** [comment]
It's really easy and fast to setup. Hassle free.

**Comment by DMCK96** [comment]
Yeah this really isn't difficult at all. Unsure why this is even an issue. 

But this is not a game crack, I am aware it's being reported on as such but this is a server emulator, and as far as server emulators go this is one of the simpler ones to setup.

**Comment by VelirzX** [comment]
> Yeah this really isn't difficult at all. Unsure why this is even an issue.
> 
> But this is not a game crack, I am aware it's being reported on as such but this is a server emulator, and as far as server emulators go this is one of the simpler ones to setup.

Mhm you say so yourself, but i was dealing with this until morning and i still can't figure out how to do this.
Next time you say why this is an issue try doing it yourself your selfish motherfucking asshole this shit is impossible.
Nice ego.
![Ca123pture](https://user-images.githubusercontent.com/91828112/185534258-c8dd9e1b-64fb-47d7-a227-17eda18da8a9.PNG)
So any fixes? uncomplete config followed everything btw. im not sure about the hosts file ffs im too angry and tired to deal with this bs.

**Comment by Quakeman213** [comment]
> > Yeah this really isn't difficult at all. Unsure why this is even an issue.
> > But this is not a game crack, I am aware it's being reported on as such but this is a server emulator, and as far as server emulators go this is one of the simpler ones to setup.
> 
> Mhm you say so yourself, but i was dealing with this until morning and i still can't figure out how to do this. Next time you say why this is an issue try doing it yourself your selfish motherfucking asshole this shit is impossible. Nice ego. ![Ca123pture](https://user-images.githubusercontent.com/91828112/185534258-c8dd9e1b-64fb-47d7-a227-17eda18da8a9.PNG) So any fixes? uncomplete config followed everything btw. im not sure about the hosts file ffs im too angry and tired to deal with this bs.

You haven' configured PostgeSQL databases. You need to create database: diiis and worlds. After that - restore worlds database from worlds.backup.

**Comment by DMCK96** [comment]
> > Yeah this really isn't difficult at all. Unsure why this is even an issue.
> > But this is not a game crack, I am aware it's being reported on as such but this is a server emulator, and as far as server emulators go this is one of the simpler ones to setup.
> 
> Mhm you say so yourself, but i was dealing with this until morning and i still can't figure out how to do this. Next time you say why this is an issue try doing it yourself your selfish motherfucking asshole this shit is impossible. Nice ego. ![Ca123pture](https://user-images.githubusercontent.com/91828112/185534258-c8dd9e1b-64fb-47d7-a227-17eda18da8a9.PNG) So any fixes? uncomplete config followed everything btw. im not sure about the hosts file ffs im too angry and tired to deal with this bs.

Like I mentioned in my previous post, learn more about game server emulation and databases. You're issue is that you haven't followed the instructions and setup postgresql database and then configured your connection strings. 

Absolutely no need for the vile language though. Please be better.

**Comment by iEvengel** [comment]
After week, we releasse compiled version.
