### ISSUE TITLE
Портал в 1 Акте 

### ISSUE THREAD

**Issue by spiridonovdavid** [blizzless/blizzless-diiis#22]
Акт 1, Глава 10, "начало задания" необходимо покинуть город через верхние ворота, при выходе нас телепортирует верно, но при попытке вернутся обратно в эти же врата игра виснет и в консоли ошибка
![изображение](https://user-images.githubusercontent.com/5469867/185743068-c35360f5-80be-46af-9ba3-bde1806053bc.png)

**Comment by iEvengel** [comment]
Исправлено
