### ISSUE TITLE
Incorrect animations for Blacksmith/Jeweler/Mystic upgrade

### ISSUE THREAD

**Issue by DeKaN** [blizzless/blizzless-diiis#24]
The server doesn't play animation "returning to the original state after upgrade" when user clicks upgrade too fast.

Steps to reproduce:
1. Go to Blacksmith/Jeweler/Mystic NPC
2. Open "Upgrade" tab
3. Just click "Upgrade" button without any delay
After these steps, you can see intermediate state "upgrading" for this NPC

**Comment by DeKaN** [comment]
Also, animation doesn't play for upgrading from level 10 to level 11 and  from level 11 to level 12

**Comment by iEvengel** [comment]
while no't founded.
