### ISSUE TITLE
Аутентификация не удалась.

### ISSUE THREAD

**Issue by G0dSkiLLs** [blizzless/blizzless-diiis#25]
Подскажите, в чём может быть проблема? Версия клиента 2.7.3.82785
```
[ Info] [AuthenticationService]: ----------------------------------------------------------------
[ Info] [AuthenticationService]: Game: Diablo 3 | Version: 82785 | Platform: Wn64 | Locale: ruRU
[Error] [AuthenticationService]: Подключение не правильной версии клиента!
[ Info] [AuthenticationService]: ----------------------------------------------------------------
[Error] [RestSession]: Аутентификация неудалась: Логин - ****@mail.ru. Cоединение с REST разорвано.
Клиент - [::ffff:127.0.0.1]:65458 , отключен
```
![Screenshot 2022-08-20 200657](https://user-images.githubusercontent.com/111643779/185747574-e9c2c721-95d0-44f5-a32d-b1319ef9acad.png)

**Comment by mahaoqqsx** [comment]
Your account password is abnormal
Use the built-in account password
test@ 123456

**Comment by DeKaN** [comment]
@G0dSkiLLs Пропущен шаг 7 из README. Авторизация локальна и про реальный BNet аккаунт сервер ничего не знает

**Comment by G0dSkiLLs** [comment]
> @G0dSkiLLs Пропущен шаг 7 из README. Авторизация локальна и про реальный BNet аккаунт сервер ничего не знает

Как раз таки не пропущен. Консоль говорит что аккаунт уже существует.

**Comment by Akiro-SVN** [comment]
На сколько я вижу он ругается на версию клиента

**Comment by G0dSkiLLs** [comment]
> На сколько я вижу он ругается на версию клиента. И какой ярлык редактировали?

x64
![Screenshot 2022-08-20 215428](https://user-images.githubusercontent.com/111643779/185752720-832cdf5a-ca84-49ad-99f9-26518bf36137.png)

**Comment by Akiro-SVN** [comment]
=) отлично принял.
А ярлык какой редактировали?

**Comment by G0dSkiLLs** [comment]
> =) отлично принял. А ярлык какой редактировали?
![Screenshot 2022-08-20 215812](https://user-images.githubusercontent.com/111643779/185752863-45a565ec-6a4b-492c-b098-75efb88f0c4e.png)

**Comment by Akiro-SVN** [comment]
Попробуйте создать ярлык не тот что в папке 64, а просто в папке Д3

**Comment by G0dSkiLLs** [comment]
> Попробуйте создать ярлык не тот что в папке 64, а просто в папке Д3

Тоже самое.

**Comment by Akiro-SVN** [comment]
> > Попробуйте создать ярлык не тот что в папке 64, а просто в папке Д3
> 
> Тоже самое.

ммм что бы не хасорять все можно в мне дискорд написать я попробую тебе помочь с самого начала.grrr#0195

**Comment by G0dSkiLLs** [comment]
> > > Попробуйте создать ярлык не тот что в папке 64, а просто в папке Д3
> > 
> > 
> > Тоже самое.
> 
> ммм что бы не засорять все можно мне в дискорд написать я попробую тебе помочь с самого начала.grrr#0195

Короче, создал ещё пару аккаунтов, не вышло.
Чувак что написал первое сообщение гений, создал аккаунт "test@" и всё заработало=) Странно. Может быть консоль не чувствительна регистру. У меня там пароль состоял из латинских букв, больших и маленьких, а так же из цифр.

**Comment by Akiro-SVN** [comment]
> > > > Попробуйте создать ярлык не тот что в папке 64, а просто в папке Д3
> > > 
> > > 
> > > Тоже самое.
> > 
> > 
> > ммм что бы не засорять все можно мне в дискорд написать я попробую тебе помочь с самого начала.grrr#0195
> 
> Короче, создал ещё пару аккаунтов, не вышло. Чувак что написал первое сообщение гений, создал аккаунт "test@" и всё заработало=) Странно. Может быть консоль не чувствительна регистру. У меня там пароль состоял из латинских букв, больших и маленьких, а так же из цифр.

Огонь удачи=)
