### ISSUE TITLE
Error code 14001 while log-in

### ISSUE THREAD

**Issue by Neobi0s** [blizzless/blizzless-diiis#39]
Hello there,

Trying to play with an friend, the server is hosted on another computer at home. Everything is fine for me, but my friend always got "14001" error code while trying to log in...

I've correctly changed ``BindIP`` and ``Public`` one, opened ports and such but nothing is working for him.

EDIT: Using Windows 11 and firewall is disabled btw.

Any tips?
Thanks.

**Comment by Fcatme** [comment]
How did you solve such an error?

**Comment by JonaszRohde** [comment]
How did you fix the problem?
