### ISSUE TITLE
Выложите инструкцию по установке сервера Diablo 3: Reaper of Souls

### ISSUE THREAD

**Issue by WinsArtist** [blizzless/blizzless-diiis#4]
Всем добрый день!

Может кто, пожалуйста, выложить (видео, текст) подробную/досконально расписанную инструкцию по установке, данного сервера.

Ранее связывался с установкой серверов PW, но тут уже совсем другая виртуальная машина.

Буду очень благодарен, и признателен.

**Comment by jahjesus** [comment]
@panda_evg напиши в тг

**Comment by Akiro-SVN** [comment]
могу помочь с установкой пошагово, с скриншотами и текстом=) скинь почту

**Comment by iEvengel** [comment]
Detailed instructions will be released soon

**Comment by Mangustik73** [comment]
> могу помочь с установкой пошагово, с скриншотами и текстом=) скинь почту

Я бы тоже не отказался от Вашей помощи по установке сервера. Моя почта smirnof-s@mail.ru. Спасибо за ранее.

**Comment by Mangustik73** [comment]
> могу помочь с установкой пошагово, с скриншотами и текстом=) скинь почту

Я бы тоже не отказался от Вашей помощи по установке сервера. Моя почта smirnof-s@mail.ru. Спасибо за ранее.

**Comment by darksirduk** [comment]
> > могу помочь с установкой пошагово, с скриншотами и текстом=) скинь почту
> 
> Я бы тоже не отказался от Вашей помощи по установке сервера. Моя почта [smirnof-s@mail.ru](mailto:smirnof-s@mail.ru). Спасибо за ранее.

Скинь и мне тоже пожалуйста))) darksirduk@gmail.com
