### ISSUE TITLE
in game shop

### ISSUE THREAD

**Issue by officialskptv-dev** [blizzless/blizzless-diiis#44]
how do i use the platinum to buy stuff from store it keeps sending me to blizzard website

**Comment by v317** [comment]
Everything is unlocked. Equip from main menu before entering the game.

**Comment by Chanmanmanghub** [comment]
But the stash is not unlocked, it only has 1 page.

**Comment by Chanmanmanghub** [comment]
> Everything is unlocked. Equip from main menu before entering the game.

But the stash is not unlocked, it only has 1 page.

**Comment by pr701** [comment]
Stash is unlocked
