### ISSUE TITLE
Не выполняется вход на сервер

### ISSUE THREAD

**Issue by vipa00** [blizzless/blizzless-diiis#50]
При входе в игру получаю вот такое сообщение
![image](https://user-images.githubusercontent.com/69082518/201454697-32e8ae2d-0a7c-46f9-9440-b0c1d83376cb.png)
На консоли сервера при этом вот такие
![image](https://user-images.githubusercontent.com/69082518/201454709-ddb18446-0de1-4815-877d-fc257a50c166.png)

Что не дособрал / не так собрал?

**Comment by Hypo-Maniak** [comment]
I have the same error.

**Comment by vadimua757** [comment]
Create user account(s) using console: !account add Login Password Tag

**Comment by pr701** [comment]
Сredentials error.
