### ISSUE TITLE
Game has updated

### ISSUE THREAD

**Issue by ArgyleFelix** [blizzless/blizzless-diiis#54]
Version 2.7.4.86197 some of the server features broke

**Comment by breakingsword** [comment]
您好，我是周峰。您的邮件我已收到，我会尽快回复。

**Comment by pr701** [comment]
Server does not support this version, the supported version is listed on the project page.

**Comment by ArgyleFelix** [comment]
Then is it possible to downgrade the game?

**Comment by iamdroppy** [comment]
@ArgyleFelix  I'd like to know this as well if it's possible to clone the original binaries from Battle.NET (which I already did just in case) and reapply. Any way to get an original copy of 2.7.4.86197?

**Comment by Mikazuki-Yozora** [comment]
> Server does not support this version, the supported version is listed on the project page.
is there any way to get the supported version game client now?
thanks.

**Comment by Mikazuki-Yozora** [comment]
> Then is it possible to downgrade the game?

is there any way to get the supported version game client now?
thanks.

**Comment by iamdroppy** [comment]
it's now updated
