### ISSUE TITLE
Where can we get the proto files?

### ISSUE THREAD

**Issue by iamdroppy** [blizzless/blizzless-diiis#57]
I have searched throughout this repo, but I couldn't find anything that resembles this.

I'm searching for the protobuf files - is there anywhere I/we can get them?

Surely we can obtain them via protogen, but it would be nicer if it was in the repo somewhere.

**Comment by advocaite** [comment]
if you want the original proto files you have to extract them yourself 
im pretty sure all the probuff files are inside
[blizzless-diiis](https://github.com/blizzless/blizzless-diiis)/[src](https://github.com/blizzless/blizzless-diiis/tree/master/src)/DiIiSNet/

**Comment by iamdroppy** [comment]
@advocaite I undestand that, my question is that if you or someone has already the .proto files to add to the repo - it's possible to extract them but it would be nice if provided.

Thanks anyway, have a good week

**Comment by advocaite** [comment]
i can look i think i extracted them out ill let you know

**Comment by iamdroppy** [comment]
thanks a lot! it would be nice to have them
