### ISSUE TITLE
Client and Client link

### ISSUE THREAD

**Issue by coolzoom** [blizzless/blizzless-diiis#7]
The official client now is 2.7.4
Does anyone have a link for client version 2.7.3.82785?
Does it support only this version?
Regards!

**Comment by d2k2-git** [comment]
2.7.4 will be released next week. Are you sure you have 2.7.4 installed?

**Comment by coolzoom** [comment]
> 2.7.4 will be released next week. Are you sure you have 2.7.4 installed?

no man, I'm still downloading, which is so slow...
![image](https://user-images.githubusercontent.com/10232727/185402355-029f6033-0d1c-419f-bdbc-1c3b491676bb.png)

reading the website it says 2.7.4 is the live version.
so i thought 2.7.3.82785 was an older version from few month ago.
![image](https://user-images.githubusercontent.com/10232727/185402170-86efd2eb-2808-45c8-b112-c4ad15a3a35a.png)

**Comment by d2k2-git** [comment]
![image](https://user-images.githubusercontent.com/6248041/185406277-ce26b753-1850-48bb-82f3-48acb9347e1e.png)
you will see the correct version number shown in the battlenet lauchner after you installed it i guess.
d3planner is not an official site from blizzard. its bugged at the moment, showing wrong version number. 2.7.4.83734 is a Test version from the PTR Server. its tagged wrong.

**Comment by coolzoom** [comment]
> ![image](https://user-images.githubusercontent.com/6248041/185406277-ce26b753-1850-48bb-82f3-48acb9347e1e.png)
> you will see the correct version number shown in the battlenet lauchner after you installed it i guess.
> d3planner is not an official site from blizzard. d3planner is bugged at the moment, showing wrong version number. 2.7.4.83734 is a Test version from the PTR Server. its tagged wrong. 2.7.4 will be released next week on live servers with new build number.

Thanks for the details my friend! I will keep downloading it and have fun, I will close this issue now, cheers!
