### ISSUE TITLE
Hex editing the executable doesn't seem to work for connectivity

### ISSUE THREAD

**Issue by Sidefix** [blizzless/blizzless-diiis#73]
I have attempted to modify the executable in a hex editor to change the addresses to localhost with no success for connectivity.

**Comment by rgto** [comment]
you must to find all "actual." and replace it for localhost. Have about 6~7 to replace. The blank spaces must be filled with 00.

**Comment by advocaite** [comment]
https://img001.prntscr.com/file/img001/pSI9BzDTQiaudbtp9Jqc8g.png
https://img001.prntscr.com/file/img001/aq0IoXLhT-WXujlEesHUSA.png

**Comment by Sidefix** [comment]
Hello @rgto ! Thanks for reaching back

I was replacing only eu., us., kr. and cn.
I was also replacing the blank spaces with 00 as well, otherwise the exe became invalid.

I will try being more comprehensive now and will get back to you.

**Comment by Sidefix** [comment]
Worked!

I think the only ones that we need to actually modify are 2; the first is the one relevant for the region of our client (in my case it's US) and there's one more generic one that's only ".actual.battle.net" with no region prefix.

Up until now I never touched any one that wasn't part of the four mentioned in my previous message.

I think the readme should be updated to clarify what needs to be modified.

Thank you so much for the help!
