### ISSUE TITLE
I need help admin commands

### ISSUE THREAD

**Issue by denneo39** [blizzless/blizzless-diiis#8]
How to use the rest of the admin commands?
Seasons work?

**Comment by advocaite** [comment]
what command are you having issue with?

and seasons are very basic the concept works but its not 100% finished working like retail

**Comment by denneo39** [comment]
To be honest, I don’t understand at all how to enter commands like spawn and others...

**Comment by denneo39** [comment]
The teleport doesn't work. When calling a map, signatures of portal points disappear, sometimes NPCs disappear

**Comment by advocaite** [comment]
!commands give list

when looking at things to spawn i use the dict.cs file as a reference

**Comment by iEvengel** [comment]
Detailed instructions will be released soon
