### ISSUE TITLE
Enable PR from new contributors

### ISSUE THREAD

**Issue by iamdroppy** [blizzless/blizzless-diiis#83]
I'd like to contribute to the project but it's currently locked, I'm doing tests on newest build every time I can and I would like to contribute to the code as well. Maybe it's a local issue, I'm not sure.

**Comment by advocaite** [comment]
you can make pull requests  and if there good they should be accepted

**Comment by Sh4d0v** [comment]
@iamdroppy  just folk source for yourself

**Comment by iamdroppy** [comment]
Thanks gentlement. first time contributing to an OS project.

https://github.com/blizzless/blizzless-diiis/pull/85

Closing this now.
