### ISSUE TITLE
What is the current state of this game? Is it actually playable?

### ISSUE THREAD

**Issue by mjrawesome** [blizzless/blizzless-diiis#9]
Huge thanks to the entire blizzless team for this as well as other great releases!

I wanted to find out, from people on the team or people who actually attempted to play the game, what the current state of this release is. On Discord and here you said things like:

"The state of the project is **far from ideal**"
"[it's a] **semi-finished** product "
"Implemented the **basic mechanics** of almost all active abilities for all classes."
"Implemented artificial intelligence for **80%** of minions."
"Implemented personal artificial intelligence for **40%** of all monsters."

So... Is the game playable from start to finish? **What kind of bugs/issues can we expect**? Or perhaps the game isn't really playable at the moment and we should wait for someone else to finish the development?

**Comment by advocaite** [comment]
the game is playable you can go through act 1-5 you may see strange things in quest some encounters are not polished but base 1-5 works and is completable
adventure mode works rifts are very very basic DLRG is what gerneates random worlds this need alot of attention as you can get some werid level generation you will see (mulitple exits hallways with out connections for the most part all areas can have a start and end entrance that is pathable)

AI needs work as alot of monsters dont have proper AI and use default AI
boss fights need work

everything is still in its infancy so yes from basic to correct as is in retail definitely alot of work

so playable is really a opinion for each person
for me its playable as im interested in development and tinkering with game
now there is a retail source some may get interested into fixing it we may get teams working like the wow teams do this would be great escially with open source.


every update though new things must be found like new opcodes
any new proto additions
any file format changes
attributes all this stuff is reverse engerneered from client and packets with live server
people who do this are few and far between 

but yes totally playable just expect bug crashes and anything that may happen can happen
