### ISSUE TITLE
Branch strategy

### ISSUE THREAD

**Issue by goremykin** [blizzless/blizzless-diiis#96]
Hi guys! Could you describe in a few words your branch strategy? What branch should be used by regular users and what branch is recommended to use by developers as base for pull requests?

**Comment by iamdroppy** [comment]
Community is where PR should go to.

**Comment by goremykin** [comment]
@iamdroppy, It not compiling, that is why I had some doubts :)

**Comment by goremykin** [comment]
@iamdroppy, Thanks for the answer
